# Site settings
title:              "Transformative"
email:              "ben_doherty@bvn.com.au"
description:        "Write an awesome description for your new site here. trigger "
baseurl:            "/transformative" # the subpath of your site, e.g. /blog/
url:                "http://bvn-architecture.github.io" # the base hostname & protocol for your site
twitter_username:   "architecturebvn"
github_username:    "bvn-architecture"
facebook-publisher: "https://www.facebook.com/pages/BVN-Architecture/131354776914013?fref=ts"
publisher:          "BVN"
publisher_website:  "http://bvn.com.au/"

# Build settings
markdown:     "kramdown"

encoding:     "utf-8"
permalink:    "none"
highlighter:  "rouge"

sass:
    sass_dir: _sass

source:       transformative

# picture tag
picture:
  source: assets/images/_fullsize
  output: generated
  markup: picture
  presets:
    # Full width pictures
    default:
      ppi: [1, 1.5]
      attr:
        class: blog-full
        itemprop: image
      source_lrg:
        media: "(min-width: 40em)"
        width: 700
      source_med:
        media: "(min-width: 30em)"
        width: 450
      source_default:
        width: 350
        height: 200
    # Half width pictures
    half:
      ppi: [1, 1.5]
      attr:
        data-location: "{{location}}"
        data-active: nil
      source_lrg:
        media: "(min-width: 40em)"
        width: 400
      source_med:
        media: "(min-width: 30em)"
        width: 250
      source_default:
        width: 350
    # Self-set resolution sources. Useful if you don't want a 1:1 image size to dppx ratio.
    gallery:
      source_wide_hi:
        media: "(min-width: 40em) and (min-resolution: 1.5dppx)"
        width: 900
        height: 600
      source_wide:
        media: "(min-width: 40em)"
        width: 600
        height: 400
      source_default:
        width: 250
        height: 250